services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge